# Generated by Django 4.2.10 on 2025-11-11 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_task_timestamps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created',
        ),
        migrations.RemoveField(
            model_name='task',
            name='finished',
        ),
    ]
